name: Basic Integration Continues

on:
  pull_request:
    branches: [develop]
jobs:
  basic_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
